/*
 * Template group component_css
 * Compiled on Thu Feb 20 2020 08:16:51 GMT+0530 (India Standard Time)
 */
var path = require("path");
var base = path.dirname(module.filename);

function getInstance(st, group) {
    "use strict";
var r;
var gFile = "component_css"; 

group.name = "component_css";





//
// Template /component_css
//
r = function(w, rc) {
    var g = this.owningGroup,
        s = this.scope;
    
    w.write("// Custom css added //");
    w.write("\n");
    w.write(".wordpressalignment {");
    w.write("\n");
    w.pushIndentation("    ");
    w.write("padding: 6em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin-right: 1em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("margin-bottom: 2em;");
    w.popIndentation();
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("@media only screen and (max-width : 320px) and (max-height : 570px) {");
    w.write("\n");
    w.pushIndentation("    ");
    w.write(".wordpressalignment {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("padding: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-left: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-right: 0em;\t");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-bottom: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("@media only screen and (min-width : 375px) and (max-width : 812px) {");
    w.write("\n");
    w.pushIndentation("    ");
    w.write(".wordpressalignment {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("padding: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-left: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-right: 0em;\t");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-bottom: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("@media only screen and (min-width : 375px) and (max-width : 812px) and (orientation : portrait) {");
    w.write("\n");
    w.pushIndentation("    ");
    w.write(".wordpressalignment {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("padding: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-left: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-right: 0em;\t");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-bottom: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("@media only screen and (min-width : 375px) and (max-width : 667px) {");
    w.write("\n");
    w.pushIndentation("    ");
    w.write(".wordpressalignment {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("padding: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-left: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-right: 0em;\t");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-bottom: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("@media only screen and (min-width : 414px) and (max-width : 736px) and (orientation : landscape) {");
    w.write("\n");
    w.pushIndentation("    ");
    w.write(".wordpressalignment {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("padding: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-left: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-right: 0em;\t");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-bottom: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("@media only screen and (min-width : 414px) and (max-width : 736px) and (orientation : portrait) {");
    w.write("\n");
    w.pushIndentation("    ");
    w.write(".wordpressalignment {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("padding: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-left: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-right: 0em;\t");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-bottom: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("\n");
    w.write("@media only screen and (min-width: 768px) and (max-width: 1024px) {");
    w.write("\n");
    w.pushIndentation("    ");
    w.write(".wordpressalignment {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("padding: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-left: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-right: 0em;\t");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-bottom: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("\n");
    w.write("@media only screen and (min-width: 834px) and (max-width: 1112px) {");
    w.write("\n");
    w.pushIndentation("    ");
    w.write(".wordpressalignment {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("padding: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-left: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("\t\t");
    w.write("margin-right: 0em;\t");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-bottom: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("@media only screen and (min-width: 768px) and (max-width: 1024px) {");
    w.write("\n");
    w.pushIndentation("    ");
    w.write(".wordpressalignment {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("padding-top: 15em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-left: 7em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-right: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-bottom: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("@media only screen and (min-width: 1024px) and (max-width: 1366px) and (orientation:portrait) {");
    w.write("\n");
    w.pushIndentation("    ");
    w.write(".wordpressalignment {");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("padding-top: 15em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-left: 7em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-right: 0em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("text-align: left;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("        ");
    w.write("margin-bottom: 2em;");
    w.popIndentation();
    w.write("\n");
    w.pushIndentation("    ");
    w.write("}");
    w.popIndentation();
    w.write("\n");
    w.write("}");
    w.write("\n");
    w.write("\n");
    w.write("// Wordpress css added below //");
    w.write("\n");
    if (st.test(st.prop(s, g, rc, s.object, "tag", { file: gFile, line: 120, column: 11 }))) {
    
        st.write(w, s, g, rc, (function() {
        var tp = [],
        attr = st.prop(s, g, rc, s.object, "tag", { file: gFile, line: 120, column: 24 });
        tp.push(st.makeSubTemplate(g, function(w, rc) {
            var g = this.owningGroup,
            s = this.scope;
            
                     st.write(w, s, g, rc, s.name);
            }, [
            { name: "name"     }
            ])); 
        return st.map(attr, tp);
        })(), {separator: "\n"});
    
    
    }
};
r.args = [
        { name: "object"     }
];
group.addTemplate("/component_css", r); 


return group;
}
getInstance.base = base;

module.exports = getInstance;